version: '3'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_podman
    environment:
      - SERVICES=s3
      - S3_PORT=4572
      - DEBUG=1
    ports:
      - "4566-4599:4566-4599"
      - "4572:4572"
    volumes:
      - ./localstack:/tmp/localstack
